package com.drepair.mapper;

import com.drepair.po.Eval;
import com.drepair.po.EvalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int countByExample(EvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByExample(EvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByPrimaryKey(Integer evalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insert(Eval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insertSelective(Eval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    List<Eval> selectByExample(EvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    Eval selectByPrimaryKey(Integer evalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") Eval record, @Param("example") EvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExample(@Param("record") Eval record, @Param("example") EvalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKeySelective(Eval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKey(Eval record);
}