package com.drepair.mapper;

import com.drepair.po.Hmr;
import com.drepair.po.HmrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HmrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int countByExample(HmrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByExample(HmrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByPrimaryKey(Integer hmrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insert(Hmr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insertSelective(Hmr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    List<Hmr> selectByExample(HmrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    Hmr selectByPrimaryKey(Integer hmrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") Hmr record, @Param("example") HmrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExample(@Param("record") Hmr record, @Param("example") HmrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKeySelective(Hmr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKey(Hmr record);
}