package com.drepair.mapper;

import com.drepair.po.Img;
import com.drepair.po.ImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int countByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int insertSelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    List<Img> selectByExample(ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    Img selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") Img record, @Param("example") ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByExample(@Param("record") Img record, @Param("example") ImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKeySelective(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    int updateByPrimaryKey(Img record);
}