package com.drepair.po;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String adminPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String adminIcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String adminPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_name
     *
     * @return the value of admin.admin_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_name
     *
     * @param adminName the value for admin.admin_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_pwd
     *
     * @return the value of admin.admin_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_pwd
     *
     * @param adminPwd the value for admin.admin_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd == null ? null : adminPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_icard
     *
     * @return the value of admin.admin_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getAdminIcard() {
        return adminIcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_icard
     *
     * @param adminIcard the value for admin.admin_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminIcard(String adminIcard) {
        this.adminIcard = adminIcard == null ? null : adminIcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_phone
     *
     * @return the value of admin.admin_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_phone
     *
     * @param adminPhone the value for admin.admin_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }
}