package com.drepair.po;

public class Hmr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer hmrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String hmrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String hmrPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_floor
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String hmrFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String hmrIcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hmr.hmr_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String hmrPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_id
     *
     * @return the value of hmr.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getHmrId() {
        return hmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_id
     *
     * @param hmrId the value for hmr.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrId(Integer hmrId) {
        this.hmrId = hmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_name
     *
     * @return the value of hmr.hmr_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getHmrName() {
        return hmrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_name
     *
     * @param hmrName the value for hmr.hmr_name
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrName(String hmrName) {
        this.hmrName = hmrName == null ? null : hmrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_pwd
     *
     * @return the value of hmr.hmr_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getHmrPwd() {
        return hmrPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_pwd
     *
     * @param hmrPwd the value for hmr.hmr_pwd
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrPwd(String hmrPwd) {
        this.hmrPwd = hmrPwd == null ? null : hmrPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_floor
     *
     * @return the value of hmr.hmr_floor
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getHmrFloor() {
        return hmrFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_floor
     *
     * @param hmrFloor the value for hmr.hmr_floor
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrFloor(String hmrFloor) {
        this.hmrFloor = hmrFloor == null ? null : hmrFloor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_icard
     *
     * @return the value of hmr.hmr_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getHmrIcard() {
        return hmrIcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_icard
     *
     * @param hmrIcard the value for hmr.hmr_icard
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrIcard(String hmrIcard) {
        this.hmrIcard = hmrIcard == null ? null : hmrIcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hmr.hmr_phone
     *
     * @return the value of hmr.hmr_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getHmrPhone() {
        return hmrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hmr.hmr_phone
     *
     * @param hmrPhone the value for hmr.hmr_phone
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrPhone(String hmrPhone) {
        this.hmrPhone = hmrPhone == null ? null : hmrPhone.trim();
    }
}