package com.drepair.po;

import java.util.ArrayList;
import java.util.List;

public class HmrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public HmrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHmrIdIsNull() {
            addCriterion("hmr_id is null");
            return (Criteria) this;
        }

        public Criteria andHmrIdIsNotNull() {
            addCriterion("hmr_id is not null");
            return (Criteria) this;
        }

        public Criteria andHmrIdEqualTo(Integer value) {
            addCriterion("hmr_id =", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdNotEqualTo(Integer value) {
            addCriterion("hmr_id <>", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdGreaterThan(Integer value) {
            addCriterion("hmr_id >", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hmr_id >=", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdLessThan(Integer value) {
            addCriterion("hmr_id <", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdLessThanOrEqualTo(Integer value) {
            addCriterion("hmr_id <=", value, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdIn(List<Integer> values) {
            addCriterion("hmr_id in", values, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdNotIn(List<Integer> values) {
            addCriterion("hmr_id not in", values, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdBetween(Integer value1, Integer value2) {
            addCriterion("hmr_id between", value1, value2, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hmr_id not between", value1, value2, "hmrId");
            return (Criteria) this;
        }

        public Criteria andHmrNameIsNull() {
            addCriterion("hmr_name is null");
            return (Criteria) this;
        }

        public Criteria andHmrNameIsNotNull() {
            addCriterion("hmr_name is not null");
            return (Criteria) this;
        }

        public Criteria andHmrNameEqualTo(String value) {
            addCriterion("hmr_name =", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameNotEqualTo(String value) {
            addCriterion("hmr_name <>", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameGreaterThan(String value) {
            addCriterion("hmr_name >", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameGreaterThanOrEqualTo(String value) {
            addCriterion("hmr_name >=", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameLessThan(String value) {
            addCriterion("hmr_name <", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameLessThanOrEqualTo(String value) {
            addCriterion("hmr_name <=", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameLike(String value) {
            addCriterion("hmr_name like", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameNotLike(String value) {
            addCriterion("hmr_name not like", value, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameIn(List<String> values) {
            addCriterion("hmr_name in", values, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameNotIn(List<String> values) {
            addCriterion("hmr_name not in", values, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameBetween(String value1, String value2) {
            addCriterion("hmr_name between", value1, value2, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrNameNotBetween(String value1, String value2) {
            addCriterion("hmr_name not between", value1, value2, "hmrName");
            return (Criteria) this;
        }

        public Criteria andHmrPwdIsNull() {
            addCriterion("hmr_pwd is null");
            return (Criteria) this;
        }

        public Criteria andHmrPwdIsNotNull() {
            addCriterion("hmr_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andHmrPwdEqualTo(String value) {
            addCriterion("hmr_pwd =", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdNotEqualTo(String value) {
            addCriterion("hmr_pwd <>", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdGreaterThan(String value) {
            addCriterion("hmr_pwd >", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdGreaterThanOrEqualTo(String value) {
            addCriterion("hmr_pwd >=", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdLessThan(String value) {
            addCriterion("hmr_pwd <", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdLessThanOrEqualTo(String value) {
            addCriterion("hmr_pwd <=", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdLike(String value) {
            addCriterion("hmr_pwd like", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdNotLike(String value) {
            addCriterion("hmr_pwd not like", value, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdIn(List<String> values) {
            addCriterion("hmr_pwd in", values, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdNotIn(List<String> values) {
            addCriterion("hmr_pwd not in", values, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdBetween(String value1, String value2) {
            addCriterion("hmr_pwd between", value1, value2, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrPwdNotBetween(String value1, String value2) {
            addCriterion("hmr_pwd not between", value1, value2, "hmrPwd");
            return (Criteria) this;
        }

        public Criteria andHmrFloorIsNull() {
            addCriterion("hmr_floor is null");
            return (Criteria) this;
        }

        public Criteria andHmrFloorIsNotNull() {
            addCriterion("hmr_floor is not null");
            return (Criteria) this;
        }

        public Criteria andHmrFloorEqualTo(String value) {
            addCriterion("hmr_floor =", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorNotEqualTo(String value) {
            addCriterion("hmr_floor <>", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorGreaterThan(String value) {
            addCriterion("hmr_floor >", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorGreaterThanOrEqualTo(String value) {
            addCriterion("hmr_floor >=", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorLessThan(String value) {
            addCriterion("hmr_floor <", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorLessThanOrEqualTo(String value) {
            addCriterion("hmr_floor <=", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorLike(String value) {
            addCriterion("hmr_floor like", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorNotLike(String value) {
            addCriterion("hmr_floor not like", value, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorIn(List<String> values) {
            addCriterion("hmr_floor in", values, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorNotIn(List<String> values) {
            addCriterion("hmr_floor not in", values, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorBetween(String value1, String value2) {
            addCriterion("hmr_floor between", value1, value2, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrFloorNotBetween(String value1, String value2) {
            addCriterion("hmr_floor not between", value1, value2, "hmrFloor");
            return (Criteria) this;
        }

        public Criteria andHmrIcardIsNull() {
            addCriterion("hmr_icard is null");
            return (Criteria) this;
        }

        public Criteria andHmrIcardIsNotNull() {
            addCriterion("hmr_icard is not null");
            return (Criteria) this;
        }

        public Criteria andHmrIcardEqualTo(String value) {
            addCriterion("hmr_icard =", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardNotEqualTo(String value) {
            addCriterion("hmr_icard <>", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardGreaterThan(String value) {
            addCriterion("hmr_icard >", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardGreaterThanOrEqualTo(String value) {
            addCriterion("hmr_icard >=", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardLessThan(String value) {
            addCriterion("hmr_icard <", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardLessThanOrEqualTo(String value) {
            addCriterion("hmr_icard <=", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardLike(String value) {
            addCriterion("hmr_icard like", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardNotLike(String value) {
            addCriterion("hmr_icard not like", value, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardIn(List<String> values) {
            addCriterion("hmr_icard in", values, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardNotIn(List<String> values) {
            addCriterion("hmr_icard not in", values, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardBetween(String value1, String value2) {
            addCriterion("hmr_icard between", value1, value2, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrIcardNotBetween(String value1, String value2) {
            addCriterion("hmr_icard not between", value1, value2, "hmrIcard");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneIsNull() {
            addCriterion("hmr_phone is null");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneIsNotNull() {
            addCriterion("hmr_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneEqualTo(String value) {
            addCriterion("hmr_phone =", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneNotEqualTo(String value) {
            addCriterion("hmr_phone <>", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneGreaterThan(String value) {
            addCriterion("hmr_phone >", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("hmr_phone >=", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneLessThan(String value) {
            addCriterion("hmr_phone <", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneLessThanOrEqualTo(String value) {
            addCriterion("hmr_phone <=", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneLike(String value) {
            addCriterion("hmr_phone like", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneNotLike(String value) {
            addCriterion("hmr_phone not like", value, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneIn(List<String> values) {
            addCriterion("hmr_phone in", values, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneNotIn(List<String> values) {
            addCriterion("hmr_phone not in", values, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneBetween(String value1, String value2) {
            addCriterion("hmr_phone between", value1, value2, "hmrPhone");
            return (Criteria) this;
        }

        public Criteria andHmrPhoneNotBetween(String value1, String value2) {
            addCriterion("hmr_phone not between", value1, value2, "hmrPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmr
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 09 15:19:34 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hmr
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}