package com.drepair.po;

import java.util.Date;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_url
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_datetime
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Date imgDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_id
     *
     * @return the value of img.img_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_id
     *
     * @param imgId the value for img.img_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_url
     *
     * @return the value of img.img_url
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_url
     *
     * @param imgUrl the value for img.img_url
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_datetime
     *
     * @return the value of img.img_datetime
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Date getImgDatetime() {
        return imgDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_datetime
     *
     * @param imgDatetime the value for img.img_datetime
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setImgDatetime(Date imgDatetime) {
        this.imgDatetime = imgDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.order_id
     *
     * @return the value of img.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.order_id
     *
     * @param orderId the value for img.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}