package com.drepair.po;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.stu_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_state
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_start_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Date orderStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_over_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Date orderOverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer hmrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_room
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String orderRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_sort
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer orderSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.repairer_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private Integer repairerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_info
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    private String orderInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.stu_id
     *
     * @return the value of order.stu_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.stu_id
     *
     * @param stuId the value for order.stu_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_state
     *
     * @return the value of order.order_state
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_state
     *
     * @param orderState the value for order.order_state
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_start_time
     *
     * @return the value of order.order_start_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Date getOrderStartTime() {
        return orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_start_time
     *
     * @param orderStartTime the value for order.order_start_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderStartTime(Date orderStartTime) {
        this.orderStartTime = orderStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_over_time
     *
     * @return the value of order.order_over_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Date getOrderOverTime() {
        return orderOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_over_time
     *
     * @param orderOverTime the value for order.order_over_time
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderOverTime(Date orderOverTime) {
        this.orderOverTime = orderOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.hmr_id
     *
     * @return the value of order.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getHmrId() {
        return hmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.hmr_id
     *
     * @param hmrId the value for order.hmr_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setHmrId(Integer hmrId) {
        this.hmrId = hmrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_room
     *
     * @return the value of order.order_room
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getOrderRoom() {
        return orderRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_room
     *
     * @param orderRoom the value for order.order_room
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderRoom(String orderRoom) {
        this.orderRoom = orderRoom == null ? null : orderRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_sort
     *
     * @return the value of order.order_sort
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_sort
     *
     * @param orderSort the value for order.order_sort
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderSort(Integer orderSort) {
        this.orderSort = orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.admin_id
     *
     * @return the value of order.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.admin_id
     *
     * @param adminId the value for order.admin_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.repairer_id
     *
     * @return the value of order.repairer_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public Integer getRepairerId() {
        return repairerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.repairer_id
     *
     * @param repairerId the value for order.repairer_id
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setRepairerId(Integer repairerId) {
        this.repairerId = repairerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_info
     *
     * @return the value of order.order_info
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public String getOrderInfo() {
        return orderInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_info
     *
     * @param orderInfo the value for order.order_info
     *
     * @mbggenerated Sun Jul 09 15:19:34 CST 2017
     */
    public void setOrderInfo(String orderInfo) {
        this.orderInfo = orderInfo == null ? null : orderInfo.trim();
    }
}